import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#1C2E4A',
          50: '#E8EDF3',
          100: '#C6D2DF',
          200: '#97AFCA',
          300: '#6889AF',
          400: '#3D6394',
          500: '#1C2E4A',
          600: '#162540',
          700: '#101B30',
          800: '#0B1220',
          900: '#060A12',
        },
        navy: {
          DEFAULT: '#1C2E4A',
          900: '#1C2E4A',
          800: '#1C2E4A',
          700: '#1C2E4A',
        },
        accent: {
          DEFAULT: '#5BC0EB',
          50: '#F0FAFE',
          100: '#D6F0FB',
          200: '#A3DBF6',
          300: '#70C6F1',
          400: '#5BC0EB',
          500: '#2AAEE0',
          600: '#1A8DB9',
          700: '#136B8C',
          800: '#0C495E',
          900: '#062630',
          light: '#5BC0EB',
          glow: '#5BC0EB',
        },
        neutral: {
          50: '#F5F7FA',
          100: '#E2E8F0',
          200: '#CBD5E1',
          300: '#94A3B8',
          400: '#64748B',
          500: '#475569',
          600: '#334155',
          700: '#1E293B',
          800: '#0F172A',
          900: '#020617',
        },
        ink: '#1A1A2E',
        deep: '#1C2E4A',
        steel: '#1C2E4A',
        surface: {
          DEFAULT: '#F5F7FA',
          light: '#F5F7FA',
        },
        mist: 'rgba(255,255,255,0.07)',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Helvetica Neue', 'Arial', 'sans-serif'],
        display: ['var(--font-Sans-serif)', 'Helvetica', 'Arial', 'sans-serif'],
        title: ['var(--font-Sans-serif)', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['var(--font-Sans-serif)', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem', letterSpacing: '0.08em' }],
        'display-sm': ['2.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['3.5rem', { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['5rem', { lineHeight: '1.0', letterSpacing: '-0.025em', fontWeight: '700' }],
        'display-xl': ['6.5rem', { lineHeight: '0.95', letterSpacing: '-0.03em', fontWeight: '700' }],
        hero: ['clamp(3.75rem, 6.5vw, 6.5rem)', { lineHeight: '1.02', fontWeight: '400', letterSpacing: '-0.025em' }],
        section: ['clamp(2.25rem, 3.5vw, 3.75rem)', { lineHeight: '1.08', fontWeight: '400', letterSpacing: '-0.015em' }],
        'card-title': ['clamp(1.2rem, 1.8vw, 1.5rem)', { lineHeight: '1.2', fontWeight: '400', letterSpacing: '-0.01em' }],
        'body-lg': ['clamp(1rem, 1.2vw, 1.125rem)', { lineHeight: '1.75', fontWeight: '300' }],
        'case-study-metric': ['clamp(3rem, 5vw, 5rem)', { lineHeight: '0.95', fontWeight: '400', letterSpacing: '-0.03em' }],
        tag: ['0.72rem', { letterSpacing: '0.22em', fontWeight: '700' }],
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
        30: '7.5rem',
        section: 'clamp(4rem, 6vw, 6rem)',
        'section-lg': 'clamp(5rem, 8vw, 8rem)',
        'container-padding': 'clamp(1.25rem, 4vw, 3.5rem)',
        'section-y': '6rem',
        'section-y-sm': '3.5rem',
        'section-x': '5rem',
        'section-x-sm': '1.25rem',
        'content-gap': '3rem',
        'card-gap': '1.25rem',
        'card-pad': '2rem',
        'card-pad-sm': '1.25rem',
      },
      borderRadius: {
        none: '0',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      letterSpacing: {
        tag: '0.25em',
        wide: '0.12em',
        wider: '0.2em',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.22, 1, 0.36, 1)',
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      animation: {
        ticker: 'ticker 30s linear infinite',
        'radar-sweep': 'radarSweep 5s linear infinite',
        blob: 'blob 14s ease-in-out infinite',
        'pulse-dot': 'pulseDot 2s ease-in-out infinite',
        'float-up': 'floatUp 0.6s ease forwards',
        'grid-shift': 'gridShift 20s linear infinite',
        'orb-pulse': 'orbPulse 6s ease-in-out infinite',
        marquee: 'marqueeScroll 30s linear infinite',
        'marquee-slow': 'marqueeScroll 50s linear infinite',
        'marquee-reverse': 'marqueeScrollReverse 35s linear infinite',
      },
      keyframes: {
        ticker: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
        radarSweep: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        blob: {
          '0%, 100%': { transform: 'translate(0,0) scale(1)' },
          '33%': { transform: 'translate(20px,-15px) scale(1.04)' },
          '66%': { transform: 'translate(-15px,12px) scale(0.97)' },
        },
        pulseDot: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(91,192,235,0.4)' },
          '50%': { boxShadow: '0 0 0 6px rgba(91,192,235,0)' },
        },
        floatUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        gridShift: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(60px)' },
        },
        orbPulse: {
          '0%, 100%': { transform: 'translateY(-50%) scale(1)', opacity: '0.7' },
          '50%': { transform: 'translateY(-50%) scale(1.1)', opacity: '1' },
        },
        marqueeScroll: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        marqueeScrollReverse: {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      backgroundImage: {
        'grid-pattern': `linear-gradient(rgba(91,192,235,0.02) 1px, transparent 1px),
          linear-gradient(90deg, rgba(91,192,235,0.02) 1px, transparent 1px)`,
        'grid-pattern-light': `linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px),
          linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px)`,
        'grid-pattern-v': `linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)`,
      },
      backgroundSize: {
        grid: '60px 60px',
        'grid-sm': '50px 50px',
        'grid-v': '20vw 100%',
      },
    },
  },
  plugins: [],
};

export default config;
